### ISSUE TITLE
hele me please 

### ISSUE THREAD

**Issue by jsonwang** [BradLarson/GPUImage3#101]
i want add subtitle into a mp4 video file , can i use a.  uilabel view ?   tell me how to do ?

**Comment by 008v** [comment]
you should use AVSynchronizedLayer to display a CALayer.
and use AVVideoCompositionCoreAnimationTool to export CALayer into a video.

**Comment by 008v** [comment]
or you could create a CGContext with CVPixelBuffer, and draw CALayer in context.
