### ISSUE TITLE
Xcode 12 - Camera.swift not building 

### ISSUE THREAD

**Issue by madadoux** [BradLarson/GPUImage3#106]
since upgrading to Xcode 12 that supports ios 14 
this framework not building because of this line 

`        let supportedPixelFormats = videoOutput.availableVideoPixelFormatTypes
`
it says 
 **Type 'AVCaptureVideoDataOutput' has no member 'availableVideoPixelFormatTypes'** 

Please we need a fix to this issue I don't understand what it means so I can't find alternative for it 

system info : 
xcode Version 12.0.1 (12A7300)
macos : 10.15.5 (19F101)

**Comment by SijieChenHotstar** [comment]
it's Xcode issue.  
check https://developer.apple.com/forums/thread/658471

**Comment by madadoux** [comment]
Thank you sijie
