### ISSUE TITLE
Chroma Key

### ISSUE THREAD

**Issue by CharlyPico** [BradLarson/GPUImage3#108]
Hi there!

I've been using GPUImage 1 and 2 for a while and looks like on GPUImage 3 there is no reference to ChromaKey or Background Color Rendering as it used to.

Will Chroma Keying be available in a future build with Metal?

Thanks,
Charlie.

**Comment by BradLarson** [comment]
Chroma keying has since been added to the framework, and I've updated the README to reflect this.
