### ISSUE TITLE
How to save camera output?

### ISSUE THREAD

**Issue by junjielu** [BradLarson/GPUImage3#19]
Hi there,

Thanks for your great job. I'm new to GPUImage, and I'm wondering if there is something like 'output'? Since we use `Camera` as input, there is reasonable to be a output. However, I cannot find something like this.

Looking forward to your reply~

**Comment by BradLarson** [comment]
Many of the outputs are not yet functional in this version of the project. In the meantime, you can look at GPUImage2 that has all of these implemented using OpenGL under the hood.

When the outputs become functional here, you can switch to this project and use the same API, only Metal under the hood.

**Comment by junjielu** [comment]
Thanks for your reply~
