### ISSUE TITLE
BulgeDistortion metal shader contains a number of errors, rendering it unusable

### ISSUE THREAD

**Issue by DoctorManhattanDDS** [BradLarson/GPUImage3#27]
The BulgeDistortion operation and Metal shader don't have any Target Membership. When added to the GPUImage_iOS Target, the build fails due to a considerable number of errors (revealed through attempting to compile the file using xcrun metal).

**Comment by BradLarson** [comment]
This was fixed in the following commit:

https://github.com/BradLarson/GPUImage3/commit/06c06f9ab1a3db6224b610ebcf09c8d46a5ac76e
