### ISSUE TITLE
Integrating a new project with GPUImage3 failed

### ISSUE THREAD

**Issue by allenlinli** [BradLarson/GPUImage3#37]
Hello, I am new to GPUImage3, and I try to integrate GPUImage3 in a completely new Swift project, but it shows some error:
<img width="1264" alt="screen shot 2019-03-07 at 11 40 59 am" src="https://user-images.githubusercontent.com/849911/53930863-ee2e5d00-40cd-11e9-8a59-9fb85dd8ef7e.png">

My environment is Xcode 10.1 (10B61).
I only followed the steps in [Using GPUImage in a Mac or iOS application](https://github.com/BradLarson/GPUImage3#using-gpuimage-in-a-mac-or-ios-application) in a new created Swift project.

Maybe I should do some extra steps like add "MetalKit" or something?

**Comment by allenlinli** [comment]
Same problem in the current examples

**Comment by allenlinli** [comment]
I found it only works on real device, not simulator.

**Comment by BradLarson** [comment]
Yeah, unfortunately the Simulator does not currently support Metal in the way that this framework needs, so all testing needs to be done on-device and all builds need to target actual hardware. Sorry about that.
