### ISSUE TITLE
Objective C compatibility

### ISSUE THREAD

**Issue by stomper3579** [BradLarson/GPUImage3#38]
I'm trying to maintain an old project written by a contracted developer in Objective C.  Can I use this latest version?  Can it be dropped into an Objc project with cocoapods?

**Comment by BradLarson** [comment]
The GPUImage 2/3 versions have a different API than the original Objective-C GPUImage project. GPUImage 2 and 3 are intended to be drop-in compatible with each other, but not with the original GPUImage.

The API itself is also crafted to be Swift-based, and has types and features that Objective-C does not support, so it has not been intended for use in Objective-C applications. We've been purely targeting this at Swift-based applications.

Additionally, I'm not aware of any CocoaPods support for either of the Swift versions. I don't personally use CocoaPods myself, so I'm not familiar with the process of supporting that.

The original Objective-C version should still be functional and usable. Is the question motivated by the need to switch from OpenGL to Metal?
