### ISSUE TITLE
Simple Example code not build success

### ISSUE THREAD

**Issue by R3l0ad3d** [BradLarson/GPUImage3#41]
I open your simple code . when i try to build it has many error  check this error massage 
![Screenshot 2019-06-14 at 2 54 19 PM](https://user-images.githubusercontent.com/9822948/59497044-7cc42e80-8eb4-11e9-8a48-5b39a52f09ef.png)

**Comment by BradLarson** [comment]
If you are attempting to build for the Simulator, Metal is only supported there starting with macOS 10.15 and Xcode 11. You'll need both of those to compile Metal code to the Simulator.

You should be able to build to a generic device target, or to deploy on your device using older Xcode / macOS versions.
