### ISSUE TITLE
GPUImage 3 has no MovieOutput?

### ISSUE THREAD

**Issue by CharlyPico** [BradLarson/GPUImage3#44]
Hi there, I've been using GPUImage 2 for a while and realized that this GPUImage 3 version contains no MovieOutput yet, will there be an implementation for this soon?

I would love to upgrade my App to GPUImage 3, but MovieOutput is critical for my App.

Thanks! 
PD: Awesome work you are doing here, I love it.

**Comment by Maxim-Appicstars** [comment]
Hi there, seems to I face with the same issue: I need to save rendered video to file. Do GPUImage has this functionality?

**Comment by BradLarson** [comment]
As of commit https://github.com/BradLarson/GPUImage3/commit/4172241e8ca055318bff5703bfba62b7bf8b7cdc , this has now been added. It may require some performance testing and more thorough evaluation, but it appears to work within test applications brought over from GPUImage 2.

**Comment by hoangdado** [comment]
Hi @BradLarson, thanks for your working, I have tried to run SimpleVideoRecorder example but got the error "Value of type 'Camera?' has no member 'audioEncodingTarget". If I comment out two line of code in ViewController.swift `camera.audioEncodingTarget = movieOutput`  and `self.camera.audioEncodingTarget = nil`it works but the output video contains corruption (look like  glitch effect). Hopefully you will fix it soon.

**Comment by Maxim-Appicstars** [comment]
thank you @BradLarson
