### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by GiacomoLeopizzi** [BradLarson/GPUImage3#48]
Using the framework by the Swift Package Manager result in a build error on Xcode 11 (but probably also on Xcode 10.2). The reason is because in the Package.swift, line 21 there is 
`swiftLanguageVersions: [.v4]`
While the used version of swift is 4.2. To support build should be changed in 
`swiftLanguageVersions: [.v4_2, .v5]`

**Comment by ggua5470** [comment]
I also did a quick test of using GPUImage3 with Swift Package Manager.
Some compile errors pop up related to swift version.
So I guess @GiacomoLeopizzi  is right.

**Comment by BradLarson** [comment]
Should be fixed as of #133
