### ISSUE TITLE
Is gpuimage3 recommended for production use yet

### ISSUE THREAD

**Issue by geekinesis** [BradLarson/GPUImage3#58]
Hi
Thanks for updating gpuimage to metal, 
I have a number of apps using the gpuimage2 framework
I’ve experimented with gpuimage3 with some success but am not sure if you recommend using the framework in a released app yet?

**Comment by sabiland** [comment]
After some testing I quickly got metal exceptions, I do not think it is production ready.
Also I found out that some filters are missing which are present in GPUImage2.

**Comment by RedQueenCoder** [comment]
We're still in the process of porting all of the filter over from GPUImage2. We've had a few time sucks over the last year and the goal is to get this production ready by the end of the year. Thank you for being patient.

**Comment by bhallamohit** [comment]
Is it mature now?. Can we use it for production?
