### ISSUE TITLE
This project hasn't been updated for a long time. Will it be released?

### ISSUE THREAD

**Issue by Dec22gln** [BradLarson/GPUImage3#59]
It looks like the author has no time to maintain it.

**Comment by geekinesis** [comment]
It’s still being maintained, it just takes time as the developers have other commitments as well. I think the last I heard they were aiming for the end of the year for a release.

**Comment by RedQueenCoder** [comment]
Yes, the goal is to target and end of year release. I have several fixes and shaders that are done but I need to do a code review on before I merge them into the repository. We have a comprehensive list of all shaders and features that need to be completed before the end of the year and we're actively working on implementing them. We appreciate your patience.
