### ISSUE TITLE
is there something wrong in setsat function in BlendShaderTypes.metal ?

### ISSUE THREAD

**Issue by AddIcechan** [BradLarson/GPUImage3#64]
I found this code in setsat function in  BlendShaderTypes.metal .
`/* b is max, r is mid, g is min */
            c.r = mid(c.g, c.r, c.b, s);
            c.b = s;
            c.r = 0.0h;`

is it should be like this ？
`/* b is max, r is mid, g is min */
            c.r = mid(c.g, c.r, c.b, s);
            c.b = s;
            c.g = 0.0h;
`
😂

**Comment by RedQueenCoder** [comment]
Lol. I changed it and I'm blaming the guy who was here before me. Thanks! 🙃

**Comment by AddIcechan** [comment]
> Lol. I changed it and I'm blaming the guy who was here before me. Thanks! 🙃

it also exist in GPUImage2
