### ISSUE TITLE
Zoom Blur issue 

### ISSUE THREAD

**Issue by R3l0ad3d** [BradLarson/GPUImage3#65]
Fragment Function(zoomBlurFragment): argument uniform[0] from buffer(1) with offset(0) and length(12) has space for 12 bytes, but argument has a length(16).'
how can i fix this . and Motion blur code commented . is it work ?

**Comment by artsector** [comment]
@R3l0ad3d 
https://github.com/BradLarson/GPUImage3/issues/63#issuecomment-568256622

**Comment by R3l0ad3d** [comment]
thanks . there is huge memory leak in this version . i use same code for gpuimage 2 and 3 . 2 work fine no memory leak but when i use 3 there is huge leak . please look after this issue .

**Comment by AddIcechan** [comment]
I  change the zoom blur uniform struct . just exchange the center and the size position . 
```
before :

typedef struct {
    float2 center;
    float size;
} ZoomBlurUniform;

after: 

typedef struct {
    float size;
    float2 center;
} ZoomBlurUniform;
```
And I  found it work .
