### ISSUE TITLE
WhiteBalance operation doesn't work

### ISSUE THREAD

**Issue by kirillbagrinovsky** [BradLarson/GPUImage3#71]
I see we can't use White balance correction like in GPUImage 1
Now code of this operation is commented

Can you enable this code again?
I think we should change only two things to fix this operation

1.
({temperature = 1.0})()
({tint = 0.0})()

2.
constant half3x3 RGBtoYIQ = half3x3({0.299, 0.587, 0.114}, {0.596, -0.274, -0.322}, {0.212, -0.523, 0.311});
constant half3x3 YIQtoRGB = half3x3({1.0, 0.956, 0.621}, {1.0, -0.272, -0.647}, {1.0, -1.105, 1.702});

**Comment by BradLarson** [comment]
This has been fixed as of #94
