### ISSUE TITLE
memory leaks when mixing camera and movie

### ISSUE THREAD

**Issue by nikolayzhuk** [BradLarson/GPUImage3#75]
I tried to mix the camera and movie but it crashes cause of memory leaks in few sec.
        do {
            camera = try Camera(sessionPreset: .photo)
            movie = try MovieInput(url:movieURL, playAtActualSpeed:true)
            filter = ChromaKeyBlend()
            camera --> filter
            movie --> filter
            filter --> renderView
            movie.runBenchmark = true
            movie.start()
            camera.startCapture()
        } catch {
            print("Couldn't process movie with error: \(error)")
        }

Please help me

**Comment by jiangao070112** [comment]
> I tried to mix the camera and movie but it crashes cause of memory leaks in few sec.
> do {
> camera = try Camera(sessionPreset: .photo)
> movie = try MovieInput(url:movieURL, playAtActualSpeed:true)
> filter = ChromaKeyBlend()
> camera --> filter
> movie --> filter
> filter --> renderView
> movie.runBenchmark = true
> movie.start()
> camera.startCapture()
> } catch {
> print("Couldn't process movie with error: (error)")
> }
> 
> Please help me

It is the same to me.
Only you use movieInput, the memory leaks huge.

**Comment by landsv** [comment]
for me it just crashes after playing a few seconds of hd video cause of memory issue
