### ISSUE TITLE
Question only: Anyone able to do any of this in Javascript?

### ISSUE THREAD

**Issue by mgw-sbic** [BradLarson/GPUImage3#86]
Hi Brad & Co, Is there anything like this available for Javascript?

**Comment by mgw-sbic** [comment]
Just checking if JavaScript is even possible as a way to add image analysis to the browser canvas. Thank you!

**Comment by BradLarson** [comment]
Unfortunately, neither of us have done much work with JavaScript image processing, so I can't provide a recommendation for an alternative. Our focus has been on Swift (previously Objective-C) and OpenGL / Metal for use in desktop / mobile / embedded platforms.

Good luck on your search, though.
